[#186510319] Add Actions support
Moesif/moesifapi-nodejs pull request #41
Opened 2024-10-29 13:26 UTC by selectiveduplicate

## Test results
![image](https://github.com/user-attachments/assets/2dc22358-994f-4b86-af4e-bcb951aa6cbc)

### `sendAction` test

![image](https://github.com/user-attachments/assets/f1a68615-922d-46d2-9026-fbb53dfd5b8e)

![image](https://github.com/user-attachments/assets/e0f630e7-98fe-41c1-8aa7-11e6ddc10ca9)

![image](https://github.com/user-attachments/assets/7cabe5bb-f6fe-44c0-9c81-758e936ec8f3)

![image](https://github.com/user-attachments/assets/991a9602-c4db-4aad-91e5-8b454448f7a0)

### `sendActionsBatch` tests

![image](https://github.com/user-attachments/assets/11124f39-323b-437d-ba6a-6c623c4f252f)

![image](https://github.com/user-attachments/assets/e368e3c7-fac9-4e5e-aa89-2be53fe00811)

![image](https://github.com/user-attachments/assets/2027dd8f-539c-499f-8ff3-92919df5a1f2)

![image](https://github.com/user-attachments/assets/53ebba09-fec3-4817-8fe4-accccf2e4b6a)

2024-10-29 13:56 UTC, praves77 commented
Cc: @xinghengwang ^^
@selectiveduplicate 
- don't we bump up the version to publish?
- please check/include dependabot PR too.

2024-10-29 14:10 UTC, selectiveduplicate commented
@praves77 Done! Included terminal output for local tests in the description as well.

2024-10-29 16:59 UTC, xinghengwang requested changes

2024-10-29 16:59 UTC, xinghengwang commented on lib/Models/ActionModel.js
> +};
are you sure `user_agent_string` and `ip_address` doesn't need to be in the dictionary here? for handling translating form camel case to snake case?   Is it carried over in the payload without?

2024-10-29 17:26 UTC, xinghengwang commented on lib/Models/ActionModel.js
> +};
I don't remember if it is is the right place to add it, just double check the { request.userAgentString  and request.ipAddress is translated correctly snake_case for the final payload.

2024-10-30 05:42 UTC, praves77 commented
@selectiveduplicate please review the @xinghengwang comments and apply.

2024-10-30 09:23 UTC, selectiveduplicate commented
@xinghengwang You're right! They weren't being properly formatted. I've patched an implementation; let me know if there's a better way.
cc @praves77 .

2024-10-31 00:11 UTC, xinghengwang approved these changes

2024-10-31 00:11 UTC, xinghengwang approved these changes

2024-10-31 00:11 UTC, merged